@baseUrl = http://localhost:3333
@token = {{create_session.response.body.token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@example.com.br",
  "password": "123456"
}

###

# @name create_session
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@acme.com",
  "password": "123456"
}

###

# @name profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name request_password_recover
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
  "email": "guilherme@acme.com"
}

###

# @name reset_password
POST {{baseUrl}}/password/reset
Content-Type: application/json

{
  "code": "226ede3c-0bdb-43e1-a87b-9bc34a248730",
  "password": "123456"
}

