@baseUrl = http://localhost:3333
@token = {{create_session.response.body.token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@example.com.br",
  "password": "123456"
}

###

# @name create_session
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@acme.com",
  "password": "123456"
}

###

# @name create_session_github
# @prompt code Get code in https://github.com/login/oauth/authorize?client_id=your-app-client-id&redirect_uri=http://localhost:3000/api/auth/callback&scope=user:email
POST {{baseUrl}}/sessions/github
Content-Type: application/json

{
  "code": {{code}}
}

###

# @name profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name request_password_recover
POST {{baseUrl}}/password/recover
Content-Type: application/json

{
  "email": "guilherme@acme.com"
}

###

# @name reset_password
POST {{baseUrl}}/password/reset
Content-Type: application/json

{
  "code": "226ede3c-0bdb-43e1-a87b-9bc34a248730",
  "password": "123456"
}

###

# @name create_organization
POST {{baseUrl}}/organization
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "name": "GBDSANTOS", 
  "domain": "gbdsantos.dev",
  "shouldAttachUsersByDomain": true 
}

###

# @name get_membership
GET {{baseUrl}}/organizations/{slug}/membership
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_organization_by_user
# Get organization where user is a member
GET {{baseUrl}}/organizations
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_organizations
# Get details from organization
# @prompt slug Add url slug of your organization
GET {{baseUrl}}/organizations/{{slug}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name update_organization
# Update organization details
# @prompt slug Add url slug of your organization
PUT {{baseUrl}}/organizations/{{slug}}
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "name": "GBDSANTOS", 
  "domain": "gbdsantos.dev",
  "shouldAttachUsersByDomain": true 
}

###

# @name shutdown_organization
# Shutdown organization details
# @prompt slug Add url slug of your organization
DELETE {{baseUrl}}/organizations/{{slug}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_project
# Update organization details
# @prompt slug Add url slug of your organization
POST {{baseUrl}}/organizations/{{slug}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "name": "Project test 1", 
  "description": "Sample project."
}

###

# @name get_project
# @prompt slug Add url slug of your organization
# @prompt projectSlug Add project slug of your project
GET {{baseUrl}}/organizations/{{slug}}/projects/{{projectSlug}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_projects
# @prompt slug Add url slug of your organization
GET {{baseUrl}}/organizations/{{slug}}/projects
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name update_project
# @prompt slug Add url slug of your organization
# @prompt projectId Add project slug of your project
PUT {{baseUrl}}/organizations/{{slug}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "name": "Project updated 1", 
  "description": "Sample project, updated description."
}

###

# @name delete_project
# @prompt slug Add url slug of your organization
# @prompt projectId Add project slug of your project
DELETE {{baseUrl}}/organizations/{{slug}}/projects/{{projectId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_members
# @prompt slug Add url slug of your organization
GET {{baseUrl}}/organizations/{{slug}}/members
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name update_member
# @prompt slug Add url slug of your organization
# @prompt memberId Add member id of your organization
PUT {{baseUrl}}/organizations/{{slug}}/members/{{memberId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "role": "ADMIN", 
}

###

# @name remove_member_organization
# Remove member of organization //:slug/members/memberId
# @prompt memberId Add memberId in your organization
# @prompt slug Add url slug of your organization
DELETE {{baseUrl}}/organizations/{{slug}}/members/{{memberId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

# Invites Routes

# @name create_invite
# Create invite
# @prompt slug Add url slug of your organization
POST {{baseUrl}}/organizations/{{slug}}/invites
Content-Type: application/json
Authorization: Bearer {{token}}

{ 
  "email": "guilherme@example.com.br", 
  "role": "ADMIN"
}