@baseUrl = http://localhost:3333
@token = {{create_session.response.body.token}}

# @name create_user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@example.com.br",
  "password": "123456"
}

###

# @name create_session
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "name": "Guilherme Bezerra",
  "email": "guilherme@acme.com",
  "password": "123456"
}

###

# @name profile
GET {{baseUrl}}/profile
Content-Type: application/json
Authorization: Bearer {{token}}